// <auto-generated />
using System;
using Followers.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Followers.Model.Migrations
{
    [DbContext(typeof(FollowersDbContext))]
    partial class FollowersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Followers.Model.Clients.Db.Entities.EfClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rank")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Clients");

                    b.HasCheckConstraint("CK_Clients_Id", "[Id] > 0");
                });

            modelBuilder.Entity("Followers.Model.Clients.Db.Entities.EfFollower", b =>
                {
                    b.Property<int>("FollowerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FollowingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FollowerId", "FollowingId");

                    b.HasIndex("FollowingId");

                    b.ToTable("Followers");

                    b.HasCheckConstraint("CK_Followers", "[FollowerId] <> [FollowingId]");

                    b.HasCheckConstraint("CK_Followers_FollowerId", "[FollowerId] > 0");

                    b.HasCheckConstraint("CK_Followers_FollowingId", "[FollowingId] > 0");
                });

            modelBuilder.Entity("Followers.Model.Clients.Db.Entities.EfFollower", b =>
                {
                    b.HasOne("Followers.Model.Clients.Db.Entities.EfClient", "Follower")
                        .WithMany("Followers")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Followers.Model.Clients.Db.Entities.EfClient", "Following")
                        .WithMany("Followings")
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Follower");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("Followers.Model.Clients.Db.Entities.EfClient", b =>
                {
                    b.Navigation("Followers");

                    b.Navigation("Followings");
                });
#pragma warning restore 612, 618
        }
    }
}
